Factory
Vehicles* Factory::vehicle
virtual Vehicles * Factory::createVehicle(string model, double HP, double damage, double speed)=0
model HP damage speed Vehicle is returned with parameters given as attributes
Referenced by testFactory.
void Factory::setVehicle(Vehicles *v)
Referenced by AircraftFactory::createVehicle, AquaticVehicleFactory::createVehicle, LandVehicleFactory::createVehicle.
Vehicles * Factory::getVehicle()
void Factory::destroy()