ResearchAndDevelopmentCentre
vector<Vehicles*> ResearchAndDevelopmentCentre::vehicleToBeUpgraded
Referenced by addToList, notifyDevelop, printList.
void ResearchAndDevelopmentCentre::startDeveloping()
References stopDeveloping.
Referenced by testAddingToList.
void ResearchAndDevelopmentCentre::stopDeveloping()
References notifyDevelop.
Referenced by startDeveloping.
void ResearchAndDevelopmentCentre::notifyDevelop()
References vehicleToBeUpgraded.
Referenced by stopDeveloping.
void ResearchAndDevelopmentCentre::destroy()
void ResearchAndDevelopmentCentre::printList()
References vehicleToBeUpgraded.
Referenced by testAddingToList.
void ResearchAndDevelopmentCentre::addToList(Vehicles *v)
References vehicleToBeUpgraded.
Referenced by Aircraft::readyToUpgrade, AquaticVehicles::readyToUpgrade, LandVehicles::readyToUpgrade, testAddingToList.