Vehicles
string Vehicles::model
double Vehicles::HP
double Vehicles::damage
double Vehicles::speed
int Vehicles::level
string Vehicles::type
Referenced by Aircraft::Aircraft, AquaticVehicles::AquaticVehicles, clone, LandVehicles::LandVehicles, print.
Vehicles::Vehicles(string model, double HP, double damage, double speed)
string Vehicles::getModel()
double Vehicles::getHP()
double Vehicles::getDamage()
double Vehicles::getSpeed()
int Vehicles::getLevel()
Vehicles * Vehicles::clone()
References type.
Referenced by clone, testFactory, testMultipleClones, testVehicles.
Vehicles ** Vehicles::clone(int n)
References clone.
void Vehicles::update()
References incLevel.
void Vehicles::takeDamage(double dmg)
void Vehicles::incLevel()
Referenced by Aircraft::update, AquaticVehicles::update, LandVehicles::update, update.
void Vehicles::print()
References type.
Referenced by testFactory, testMultipleClones, testVehicles.
void Vehicles::attack(Vehicles *theEnemy)