main.cpp
void testVehicles(int numVehicles)
References Vehicles::clone, Vehicles::print.
Referenced by main.
void testFactory(int numVehicles)
References Vehicles::clone, Factory::createVehicle, Vehicles::print.
Referenced by main.
void testMultipleClones(int numClones)
References Vehicles::clone, Vehicles::print.
Referenced by main.
void testAddingToList()
References ResearchAndDevelopmentCentre::addToList, ResearchAndDevelopmentCentre::printList, ResearchAndDevelopmentCentre::startDeveloping.
Referenced by main.
int main()
References testAddingToList, testFactory, testMultipleClones, testVehicles.